django-2/produto/urls.py
from django.urls import path
from produto import views

app_name = "produto"

urlpatterns = [
    path('', views.index, name="index"),
    path('paginas/pagina1', views.pagina1, name="pagina1"),
    path('paginas/pagina2/', views.pagina2, name="pagina2")
]

produto/urls.py
from django.urls import path
from produto import views

app_name = "produto"

urlpatterns = [
    path('lista_produto/', views.lista_produto, name="lista_produto"),
    path('cadastra_produto/', views.cadastra_produto, name="cadastra_produto"),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from projeto import views

urlpatterns = [
    path('', views.index, name="index"),  # o name server pra qnd o href= "{% url nome_app:nomepath %}"
    path("produtod/", include('produto.urls')), #faz com que eu possa incluir urls do app produto com o endereco 'produto/app' nessa pagina
    path('admin/', admin.site.urls),
]


"""
como acessar a página index.html do projeto:
http://127.0.0.1:8000/

como acessar a página index.html de produto:
http://127.0.0.1:8000/produto/
"""

django-2/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>index</title>
</head>

<body>
    {{frase}}
    <br>
    <br>
    <a href="/produto/">acessando a página de produto usando caminho absoluto</a><br>
    <a href="produto/">acessando a página de produto usando caminho relativo</a><br>
    <a href="{% url 'produto:index' %}">acessando a página de produto usando tag url</a>
    <br><br><br>



    
    <a href="/produto/paginas/pagina1">acessando a página pagina1.html de produto usando caminho absoluto</a><br>
    <a href="/produto/paginas/pagina2/">acessando a página pagina2.html de produto usando caminho absoluto</a><br>
    <a href="{% url 'produto:pagina1' %}">acessando a página  pagina1.html de produto usando tag url</a><br>
    <a href="{% url 'produto:pagina2' %}">acessando a página  pagina2.html de produto usando tag url</a><br>
</body>

</html>

<!--como acessar a página index.html do projeto:
http://127.0.0.1:8000/

como acessar a página index.html de produto:
http://127.0.0.1:8000/produto/
-->