django-2/produto/urls.py
from django.urls import path
from produto import views

app_name = "produto"

urlpatterns = [
    path('', views.index, name="index"),
    path('paginas/pagina1', views.pagina1, name="pagina1"),
    path('paginas/pagina2/', views.pagina2, name="pagina2")
]

produto/urls.py
from django.urls import path
from produto import views

app_name = "produto"

urlpatterns = [
    path('lista_produto/', views.lista_produto, name="lista_produto"),
    path('cadastra_produto/', views.cadastra_produto, name="cadastra_produto"),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from projeto import views

urlpatterns = [
    path('', views.index, name="index"),  # o name server pra qnd o href= "{% url nome_app:nomepath %}"
    path("produtod/", include('produto.urls')), #faz com que eu possa incluir urls do app produto com o endereco 'produto/app' nessa pagina
    path('admin/', admin.site.urls),
]


"""
como acessar a página index.html do projeto:
http://127.0.0.1:8000/

como acessar a página index.html de produto:
http://127.0.0.1:8000/produto/
"""

produto/models.py
from django.db import models
from django.utils.formats import localize_input
from categoria.models import Categoria

# Create your models here.

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    descricao = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100) 
    imagem = models.CharField(max_length=50, blank=True)
    qtd_estoque= models.IntegerField()
    data_cadastro = models.DateField()
    preco = models.DecimalField(max_digits=5, decimal_places=2)
    disponivel = models.BooleanField(default=False)

    class Meta: 
        db_table = 'produto'
        # define o nome da tabela

    def __str__(self):
        return self.nome

    def get_disponivel(self): # muda o boolean de self pra 'sim' if true e 'nao' if false
        return "Sim" if (self.disponivel) else "Não"

produto/forms.py
from django import forms

from produto.models import Produto
from categoria.models import Categoria
from projeto import settings

from django.core.validators import RegexValidator

class PesquisaProdutoForm(forms.Form):

    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
        required=False)

    # <input type="text" name="nome" id="id_nome" class="form-control form-control-sm" maxlength="100">


class CadastraProdutoForm(forms.ModelForm):
    # quando é feito um formulário de entrada de dados para um modelo (uma tabela do bd)
    # é necessário usar forms.ModelForm
    class Meta:
        model = Produto
        fields = ('nome', 'descricao', 'categoria', 'data_cadastro', 'preco', 'qtd_estoque', 'imagem', 'disponivel')
        # localized_fields = ('preco',) só é necessário se for feito pela forma comentada

    """ OUTRA FORMA DE ADICIONAR OS CAMPOS (SEM PRECISAR DE ARGUMENTOS QUE JA EXISTEM)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages={'required': 'Campo obrigatório.',
                                            'unique': 'Nome de produto duplicado.'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['descricao'].error_messages={'required': 'Campo obrigatório'}
        self.fields['descricao'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['categoria'].error_messages={'required': 'Campo obrigatório'}
        self.fields['categoria'].queryset=Categoria.objects.all().order_by('nome')
        self.fields['categoria'].empty_label='--- Selecione uma categoria ---'
        self.fields['categoria'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['data_cadastro'].error_messages={'required': 'Campo obrigatório'}
        self.fields['data_cadastro'].input_formats=settings.DATE_INPUT_FORMATS
        self.fields['data_cadastro'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['preco'].min_value=0
        self.fields['preco'].error_messages={'required': 'Campo obrigatório.',
                                             'invalid': 'Valor inválido.',
                                             'max_digits': 'Mais de 5 dígitos no total.',
                                             'max_decimal_places': 'Mais de 2 dígitos decimais.',
                                             'max_whole_digits': 'Mais de 3 dígitos inteiros.'}
        self.fields['preco'].widget.attrs.update({
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['qtd_estoque'].min_value=0
        self.fields['qtd_estoque'].error_messages={
            'required': 'Campo obrigatório',
            'min_value': 'A quantidade deve ser maior ou igual a zero.'
        }
        self.fields['qtd_estoque'].widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['imagem'].error_messages={'required': 'Campo obrigatório'}
        self.fields['imagem'].validators=[
            RegexValidator(regex='^[a-z]+\.(jpg|png|gif|bmp)$', message='Nome de imagem inválido.')]
        self.fields['imagem'].widget.attrs.update({'class': 'form-control form-control-sm'})
        self.fields['imagem'].required = True

    
    
    """










    # override das definições padrões dos campos (adicionando código css aos inputs)

    nome = forms.CharField(
        error_messages = {'required' : 'Campo obrigatorio', 'unique' : 'Campo duplicado'},
        # caso o campo esteja vazio vai aparecer x, caso o nome ja existe vai aparecer y
        # isso se as propriedades unique e notnull foram definidas no modelo
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
    )

    # input nome passa a ser 
    # <input type="text" name="nome" id="id_nome" class="form-control form-control-sm" maxlength="100">

    descricao = forms.CharField(
        error_messages = {'required' : 'Campo obrigatorio'},
        # caso o campo esteja vazio vai aparecer x
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
    )

    # input descricao passa a ser 
    # <input type="text" name="descricao" id="id_descricao" class="form-control form-control-sm" maxlength="100">

    categoria = forms.ModelChoiceField(
        error_messages = {'required' : 'Campo obrigatorio'},
        # caso o campo esteja vazio vai aparecer x
        queryset = Categoria.objects.all().order_by('nome'),
        # define quais são os valores que vão aparecer na lista de categorias a ser selecionado
        # no caso por conta do metodo __str__(self): do modelo Categoria, serão retornados os
        # nomes de todas as categorias
        empty_label = "selecione uma categoria",
        # valor inicial da caixa de categorias
        widget=forms.Select(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
    )

    data_cadastro = forms.DateField(
        error_messages = {'required' : 'Campo obrigatorio', 'invalid': 'data invalida'},
        # caso o campo esteja vazio vai aparecer x, caso a data esteja errada aparece y
       
        input_formats = settings.DATE_INPUT_FORMATS,
        # formato da data a ser enviada, precisa ser definido em settings.py


        widget=forms.DateInput(attrs={'class': 'form-control form-control-sm'})
    )

    # input data_cadastro passa a ser 
    # <input type="text" name="data_cadastro" id="id_data_cadastro" class="form-control form-control-sm" maxlength="100">

    preco = forms.DecimalField(
        localize = True,
        min_value = 0,
        # valor minimo de preco
        error_messages = {'required' : 'Campo obrigatorio', 'invalid': 'preco invalida',
        'min_value': 'O valor minimo é 0', 'max_digits' : ' atingiu numero maximo de digitos',
        'max_decimal_places': 'mais de 2 digitos decimais', 'max_whole_digits':'mais de 3 inteiros'},

        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'})

    )

    # input preco passa a ser 
    # <input type="text" name="preco" id="id_preco" onkeypress="return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44" class="form-control form-control-sm" maxlength="100">

    qtd_estoque = forms.IntegerField(
        min_value = 0,
        # valor minimo de preco
        error_messages = {'required' : 'Campo obrigatorio', 'invalid': 'preco invalida',
        'min_value': 'O valor minimo é 0', 'max_digits' : ' atingiu numero maximo de digitos',
        },

        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'})

    )

    # input qtd_estoque passa a ser 
    # <input type="text" name="qtd_estoque" id="id_qtd_estoque" onkeypress="return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44" class="form-control form-control-sm" maxlength="100">


    imagem = forms.CharField(
        error_messages = {'required' : 'Campo obrigatorio'},


        validators = [RegexValidator(regex='^[a-z]+\.(jpg|png|gif|bmp)$', message="url de imagem invalido")],

        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'max-lenght': '50'})

    )

     # <input type="text" name="qtd_estoque" id="id_qtd_estoque" class="form-control form-control-sm" maxlength="50">

    """ 
    descricao = forms.BooleanField(
        error_messages = {'required' : 'Campo obrigatorio'},
        widget=forms.CheckboxInput(),
        required = False

    descricao n muda nd entao n precisa colocar

    )"""

produto/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from produto.forms import PesquisaProdutoForm, CadastraProdutoForm
from produto.models import Produto

from django.template.defaultfilters import slugify
from django.contrib import messages


def lista_produto(request):
    form = PesquisaProdutoForm(request.GET)
    if form.is_valid():
        nome = form.cleaned_data['nome']
        lista_de_produtos = Produto.objects.filter(nome__icontains=nome).order_by('nome')
        paginator = Paginator(lista_de_produtos, 3)
        pagina = request.GET.get('pagina')
        page_obj = paginator.get_page(pagina)

        print(lista_de_produtos)
        print(page_obj)

        return render(request, 'produto/pesquisa_produto.html', { 'produtos': page_obj,
                                                                  'form': form,
                                                                  'nome': nome })
    else:
        raise ValueError('Ocorreu um erro inesperado ao tentar recuperar um produto.')


def cadastra_produto(request):

    if request.POST: 
        # quando o formulário de cadastro de produto for submetido (requisição_post)
        cadastra_produto_form = CadastraProdutoForm(request.POST)
        # cria uma instância de cadastro de produto
        if cadastra_produto_form.is_valid:
            # se essa instância for válida
            try:
                # tenta cadastrar o produto no bd, se ele tiver algum erro, está parte será
                # ignorada
                produto_cadastrado = cadastra_produto_form.save(commit=False)
                # cria uma instancia sem salvar no banco de dados
                produto_cadastrado.slug = slugify(produto_cadastrado.nome)
                #adicionau m slug
                produto_cadastrado.save()
                # salva no banco
                messages.add_message(request, messages.INFO, 'Produto Cadastrado com Sucesso!')
                # mensagem de sucesso ao cadastrar produto, para mostrar na pagina html usa
                # if messages

                return render(request, 'produto/exibe_produto.html', {'produto' : produto_cadastrado})
                # renderiza uma outra pagina, a de exibiçao de produto, no mesmo url /cadastra_produto
            except ValueError:
                pass
        else:
            pass
    else:
        # se não for submetido (requisição get)
        cadastra_produto_form = CadastraProdutoForm() 

    return render(request, 'produto/cadastra_produto.html', {'form' : cadastra_produto_form})

produto/templates/produto/cadastra_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <form action="" method="POST" class="pb-4" novalidate>
      <!-- tem que adicionar novalidade no form para que ao inves de validar via js do bootstrap
      o proprio django faça a validação dos termos colocados via serverside-->
      <!-- para que o django faça a validação é necessário adicionar um token de validação
      no fim do código, isso impede por exemplo ataques colocando input maliciosos-->
      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-10">
                  {{ form.nome }}
                  {# <input type="text" name="nome" maxlength="100" required="" id="id_nome"> #}
                  {% if form.nome.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.nome.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_descricao" class="col-xl-3 font-weight-bold">Descrição</label>
               <div class="col-xl-9">
                  {{ form.descricao }}
                  {#  eh assim q vai aparecer <input type="text" name="descricao" maxlength="100" required="" id="id_descricao"> #}
                  {% if form.descricao.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.descricao.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
               <div class="col-xl-10">
                  {{ form.categoria }}
                  {% comment %}
                     <select name="categoria" required="" id="id_categoria">
                        <option value="" selected="">---------</option>
                        <option value="1">Frutas</option>
                        <option value="2">Legumes</option>
                        <option value="3">Verduras</option>
                     </select>
                  {% endcomment %}
                  {% if form.categoria.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.categoria.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_data_cadastro" class="col-xl-3 font-weight-bold">Data Cadastro</label>
               <div class="col-xl-9">
                  {{ form.data_cadastro }}
                  {# <input type="text" name="data_cadastro" required="" id="id_data_cadastro"> #}
                  {% if form.data_cadastro.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.data_cadastro.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_preco" class="col-xl-2 font-weight-bold">Preço</label>
               <div class="col-xl-10">
                  {{ form.preco }}
                  {# <input type="number" name="preco" value="0" step="0.01" required="" id="id_preco"> #}
                  {% if form.preco.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.preco.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_qtd_estoque" class="col-xl-3 font-weight-bold">Estoque</label>
               <div class="col-xl-9">
                  {{ form.qtd_estoque }}
                  {# <input type="number" name="qtd_estoque" value="0" required="" id="id_qtd_estoque"> #}
                  {% if form.qtd_estoque.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.qtd_estoque.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_imagem" class="col-xl-2 font-weight-bold">Imagem</label>
               <div class="col-xl-10">
                  {{ form.imagem }}
                  {# <input type="text" name="imagem" maxlength="50" id="id_imagem"> #}
                  {% if form.imagem.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.imagem.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <div class="offset-xl-3 col-xl-9">
                  <div class="form-check pl-0 mt-xl-0 mt-2">
                     {{ form.disponivel }}
                     {# <input type="checkbox" name="disponivel" id="id_disponivel"> #}
                     <label for="id_disponivel" class="form-check-label">Disponível?</label>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  <!-- o token fica aqui -->
                  {% csrf_token %}
                  <button id="botao" type="submit" class="btn btn-primary">
                     <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>
{% endblock %}

produto/templates/produto/exibe_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   {% if messages %}
      <div class="mb-3">
         {% for message in messages %}
            <ul class="list-group rounded">
               <li style="padding-top: 7px; padding-bottom: 7px"
                   class="list-group-item list-group-item-info">
                  {{ message }}
               </li>
            </ul>
         {% endfor %}
      </div>
   {% endif %}

   <div class="row mb-2">
      <div class="col-lg-3 col-md-4">
         <img class="mr-3" style="width: 210px"
              src="{% static 'images/produtos/' %}{{produto.imagem}}" alt="{{ produto.nome }}">
      </div>
      <div class="col-lg-9 col-md-8">
         <div class="row">
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Categoria</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ produto.categoria }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Nome</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ produto.nome }} ({{ produto.descricao }})</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Preço</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ produto.preco }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Estoque</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ produto.qtd_estoque }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Data Cadastro</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ produto.data_cadastro | date:'d/m/Y' }}</div>
            <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Disponível</div>
            <div class="col-xl-10 col-lg-9 col-8">{{ produto.get_disponivel }}</div>
         </div>
      </div>
   </div>

{% endblock %}

produto/templates/produto/pagina1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>essa é a pagina1.html de produto.</title>
</head>

<body>
    {{frase}}
</body>

</html>

produto/templates/produto/pagina2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>essa é a pagina2.html de produto.</title>
</head>

<body>
    {{frase}}
</body>

</html>

produto/templates/produto/pesquisa_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Pesquisa de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Pesquisa de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <form action="" method ='GET' class="mb-4">
      <div class='form-group row' style='margin-bottom: 10px;'>
         <label for='id_nome' class='col-lg-2 col-form-label font-weight-bold'>
            Nome
         </label>
         <div class='col-lg-10'>
            {{ form.nome }}
            <!--
            <input type='text' name='nome' id='id_nome' class='form-control form-control-sm' maxlength='100'>
            -->
         </div>
      </div>
      <div class='form-group row'>
         <div class="col-lg-10 offset-lg-2">
            <button type='submit' class='btn btn-primary'>
               <div class="d-flex align-items-center">
                  <img src="{% static 'images/skin/binoculo.png' %}" class="mr-2">Pesquisar
               </div>
            </button>
         </div>
      </div>
   </form>

   <!-- <div style="min-height: 212px"> -->
      {% if produtos %}
         <h5 class="mb-3">Lista de Produtos</h5>
         <table style='width:100%'
                class='table table-striped table-sm table-bordered table-responsive mb-4'>
            <thead>
               <tr>
                  <th class='text-center'>Imagem</th>
                  <th class='text-center'>Categoria</th>
                  <th class='text-center'>Nome/Descrição</th>
                  <th class="text-center">Disponível</th>
                  <th class='text-center'>Data de Cadastro</th>
                  <th class="text-center">Quantidade</th>
                  <th class="text-center">Preço Unitário</th>
               </tr>
            </thead>
            <tbody>
               {% for produto in produtos %}
                  <tr>
                     <td width="10%" class="text-center align-middle">
                        <img style="width:80px"
                             src="{% static 'images/produtos/' %}{{ produto.imagem }}" alt="{{ produto.nome }}">
                     </td>
                     <td width="10%" class="text-center align-middle">
                        {{ produto.categoria }}
                     </td>
                     <td width="35%" class="align-middle">
                        {{ produto.nome }} ({{ produto.descricao }})
                     </td>
                     <td width="10%" class="text-center align-middle">
                        {{ produto.get_disponivel }}
                     </td>
                     <td width="15%" class="text-center align-middle">
                        {{ produto.data_cadastro | date:'d/m/Y' }}
                     </td>
                     <td width="10%" class="text-right align-middle pr-3">
                        {{ produto.qtd_estoque }}
                     </td>
                     <td width="15%" class="text-right align-middle pr-3">
                        R$ {{ produto.preco }}
                     </td>
                  </tr>
               {% endfor %}
            </tbody>
         </table>

         <div style='font-size: 14px; margin-bottom: 28px'>
            {% if produtos.has_other_pages %}
               <ul class='pagination'>
                  {% if produtos.has_previous %}
                     <li class='page-item'><a class='page-link' href='?pagina={{ produtos.previous_page_number }}&nome={{nome}}'>Anterior</a></li>
                  {% else %}
                     <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Anterior</a></li>
                  {% endif %}
                  {% for i in produtos.paginator.page_range %}
                     {% if produtos.number == i %}
                        <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
                     {% else %}
                        <li class='page-item'><a class='page-link' href='?pagina={{ i }}&nome={{nome}}'>{{ i }}</a></li>
                     {% endif %}
                  {% endfor %}
                  {% if produtos.has_next %}
                     <li class='page-item'><a class='page-link' href='?pagina={{ produtos.next_page_number }}&nome={{nome}}'>Próxima</a></li>
                  {% else %}
                     <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Próxima</a></li>
                  {% endif %}
               </ul>
            {% endif %}
         </div>
      {% endif %}
   <!-- </div> -->

{% endblock %}